
name: PIPELINE QA (meuCI)

on:
  push:
    branches: [ "QA" ]
  pull_request:
    branches: [ "QA" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Primeiro comando Tarefa
        run: echo Usando a branch de QA
